# Camino feliz sin side effects en la BD

### Happy CRUD Path
POST  http://localhost:4000/user
Content-Type: application/json

{
  "id" : 100,
  "name": "Frijolero",
  "email": "frijolero@gmail.com",
  "display_pic_route": "frijolero.jpg"
}

###
GET  http://localhost:4000/user
###
GET  http://localhost:4000/user/100

###
GET  http://localhost:4000/user/email/frijolero@gmail.com


### Happy CRUD Path
POST  http://localhost:4000/boardgame
Content-Type: application/json

{
  "id": 100,
  "name": "Ajedrez",
  "class": "Estrategia",
  "display_pic_route": "ajedrez.jpg"
}

###
GET  http://localhost:4000/boardgame/100

###
POST  http://localhost:4000/gamemeeting
Content-Type: application/json

{
  "id": 100,
  "place": "Cabildo 66",
  "scheduled": "2021-09-05T12:42:31.00-03:00",
  "owner": 100,
  "game": 100,
  "max_players": 4
}

###
DELETE http://localhost:4000/boardgame/100

###
DELETE http://localhost:4000/user/100
