# Creacion de multiples usuarios con side effects en la BD

###
POST  http://localhost:4000/user
Content-Type: application/json

{
  "name": "Nahuel Salazar",
  "email": "nsalazar@gmail.com",
  "display_pic_route": "nahuel.jpg",
  "password": "tuty2020"
}

###
POST  http://localhost:4000/user
Content-Type: application/json

{
  "name": "Matias Kobold",
  "email": "matiask@gmail.com",
  "display_pic_route": "matias.jpg",
  "password": "tuty2020"
}
###
POST  http://localhost:4000/user
Content-Type: application/json

{
  "name": "Nicolas Diaz Pais",
  "email": "nicodiaz@gmail.com",
  "display_pic_route": "nicolas.jpg",
  "password": "tuty2020"
}
###
POST  http://localhost:4000/user
Content-Type: application/json

{
"name": "Ezequiel Cabrera",
"email": "ezecabj@gmail.com",
  "password": "tuty2020"
}


###
GET  http://localhost:4000/user

###
GET  http://localhost:4000/user/email/ezecabj@gmail.com

###
POST  http://localhost:4000/login
Content-Type: application/json

{
"email": "ezecabj@gmail.com",
"password": "tuty2020"
}
